# Generated by Django 6.0.4 on 2026-04-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='commandhistory',
            name='skill',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='enginesettings',
            name='brain_provider',
            field=models.CharField(default='rules', max_length=20),
        ),
        migrations.AddField(
            model_name='enginesettings',
            name='stt_provider',
            field=models.CharField(default='google', max_length=20),
        ),
        migrations.AddField(
            model_name='enginesettings',
            name='tts_provider',
            field=models.CharField(default='pyttsx3', max_length=20),
        ),
    ]
